version: '{build}'
skip_tags: true

configuration: Release

build: 
    project: frpGUI.sln
    parallel: true

after_build:
  - 7z a frp.7z ./* -xr!.git* -mx9
  
test: off
artifacts:
  - path: frp.7z
    name: frp
    
